blog/urls.py
from django.urls import path


from . import views
app_name = 'blog'
urlpatterns = [
    
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
    
]

personalportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include ('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField(default=timezone.now())

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost
# Create your views here.
def all_blogs(request):
    blogposts = BlogPost.objects.order_by('-date')
    print(blogposts)
    return render(request, 'blog/all_blogs.html', {'blogposts':blogposts})

def detail(request, blog_id):
    blog = get_object_or_404(BlogPost, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    print(projects)
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

Hello blog

<h2>I have written {{ blogposts.count }} blog post{{ blogposts.count|pluralize}}</h2>

{% for blogpost in blogposts %}

<a href="{% url 'blog:detail' blogpost.id %}"><h2>{{ blogpost.title }}</h2></a>
<h5>{{ blogpost.date|date:'M d Y'|upper }}</h5>
<p>{{ blogpost.description|safe|truncatechars:50 }}</p>

{% if blogpost.url%}
<p><a href="{{blogpost.url}}">Link</a></p>
{% endif %}
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>{{ blog.title }}</h1>
<h2>--{{ blog.date|date:'F jS Y' }}--</h2>
{{ blog.description }}

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kode+Mono:wght@400..700&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="icon" type="image/jpg" href="{% static "portfolio/images.jpg" %}">
    <title>Dingus Dongus</title>
</head>
  <body>
  {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container text-center">
    
        <h1>Hello there</h1>
    


{% load static %}
<a href="{% static 'portfolio/resume.pdf' %}" >Resume</a>
<br>
<a href="{% url 'blog:all_blogs'%}">My blog</a>
<br>
<img src="{% static 'portfolio/dongs.jpg' %}">

<h2 class="mt-5">Portfolio ;)</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>
<!-- {% for project in projects %}

<h2>{{ project.title }}</h2>
<p>{{ project.description }}</p>
<img src="{{ project.image.url }}" height=100 width=100>
{% if project.url%}
<p><a href="{{project.url}}">Link</a></p>
{% endif %}
{% endfor %} -->
</div>
{% endblock %}

    